"""Persistence layer (SQLite + SQLModel)."""

from .db import create_db_and_tables, get_engine, get_session
from .default_aliases import DEFAULT_FOOD_ALIASES
from .models import Food, FoodAlias, FoodLog, FoodSearchCache, LogSearchSession, Plan, User, UserConfig, UserProfileRow
from .repo import (
    add_logs,
    create_log_search_session,
    create_user,
    get_cached_food_search,
    get_food_records,
    get_foods,
    get_latest_plan_for_date,
    get_log_search_session,
    get_logs_between,
    get_profile,
    get_user,
    get_user_config,
    normalize_alias_text,
    save_plan,
    search_food_aliases,
    set_cached_food_search,
    upsert_food,
    upsert_food_alias,
    upsert_profile,
    upsert_user_config,
)
from .seed import load_food_aliases, load_foods_from_csv

__all__ = [
    "Food",
    "FoodAlias",
    "FoodLog",
    "FoodSearchCache",
    "LogSearchSession",
    "Plan",
    "User",
    "UserConfig",
    "UserProfileRow",
    "create_db_and_tables",
    "get_engine",
    "get_session",
    "DEFAULT_FOOD_ALIASES",
    "create_user",
    "create_log_search_session",
    "get_user",
    "upsert_profile",
    "get_profile",
    "upsert_user_config",
    "get_user_config",
    "normalize_alias_text",
    "upsert_food",
    "upsert_food_alias",
    "add_logs",
    "get_logs_between",
    "get_log_search_session",
    "get_foods",
    "get_food_records",
    "save_plan",
    "get_latest_plan_for_date",
    "get_cached_food_search",
    "set_cached_food_search",
    "search_food_aliases",
    "load_food_aliases",
    "load_foods_from_csv",
]
